# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "gitlab"
name = "Gitlab"
url = "https://gitlab.thalesdigital.io/tsn/innovation/projects/blog"

[social.params]
icon = "gitlab-logo-500"

