variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_STRATEGY: clone

stages:          
  - build

build-job:
  image: klakegg/hugo:0.111.3
  stage: build
  script:
    - ls themes/hugo-PaperMod
    - hugo
    - ls
  artifacts:
      paths:
      - public/