.git_vars:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1

stages:          
  - build

build-job:
  image: klakegg/hugo:0.111.3
  stage: build
  script:
    - ls
    - hugo
    - ls
  artifacts:
      paths:
      - public/