variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_STRATEGY: clone

stages:          
  - build
  - deploy

build-job:
  stage: build
  image: alpine
  script:
    - apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
    - hugo
    - ls
  artifacts:
      paths:
      - public/
push-back-to-remote:
  stage: deploy
  script:
    - git config user.email "ci-bot@example.xyz"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.thalesdigital.io/tsn/innovation/projects/blog
    - git add public/
    - git commit -m "push back from pipeline"
    - git push gitlab_origin HEAD:main -o ci.skip
