variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_STRATEGY: clone

stages:          
  - build
  - deploy

build-job:
  stage: build
  image: alpine
  script:
    - apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
    - apk add git
    - rm -rf public/blog/
    - git clone -b blog https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.thalesdigital.io/tsn/innovation/projects/blog.git public/blog/
    - hugo -d public/blog/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
    - public/blog/

push-back-to-remote:
  stage: deploy
  image: alpine
  script:
    - ls
    - apk add git
    - cd public/blog/
    - git remote set-url origin https://gitlab-ci-token:$ACCESS_TOKEN@gitlab.thalesdigital.io/tsn/innovation/projects/blog.git
    - git branch --set-upstream-to=origin/blog
    - git config user.email "ci-bot@example.xyz"
    - git config user.name "ci-bot"
    - git add *
    - git commit -m "push back from pipeline" --allow-empty
    - git push -o ci.skip
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


