stages:
  - build
  - deploy

.rules: &rules
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

build-blog:
  <<: *rules
  stage: build
  image: hugomods/hugo:exts
  script:
    - hugo --minify --enableGitInfo
    - tar czf public.tar.gz public/*
  artifacts:
    paths:
      - public.tar.gz
    expire_in: 1 minute

deploy-blog:
  <<: *rules
  stage: deploy
  image: google/cloud-sdk:502.0.0-stable
  script:
    - tar xzf public.tar.gz
    - gcloud auth activate-service-account --key-file $GCP_SA_KEY
    - gcloud storage rsync --recursive --delete-unmatched-destination-objects public gs://innovation-hub-blog
  dependencies:
    - build-blog
