variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_STRATEGY: clone

stages:          
  - build

build-job:
  stage: build
  script:
    - apt install hugo -y
    - hugo
    - ls
  artifacts:
      paths:
      - public/