baseURL: "https://example.org/"
languageCode: "en-us"
title: "Innovation Blog"
theme: "hugo-PaperMod"
publishDir: output/public/blog/
defaultContentLanguage: en
languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      tag: tags
    menu:
      main:
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Archives
          url: archives/
          weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON

Params:
  editPost:
    URL: "https://gitlab.thalesdigital.io/tsn/innovation/projects/blog/-/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  DateFormat: "2 Jan 2006"