baseURL: "https://example.org/"
languageCode: "fr-fr"
title: "Blog de l'innovation"
theme: "hugo-PaperMod"

defaultContentLanguage: fr
languages:
  fr:
    languageName: "Français"
    weight: 1
    taxonomies:
      tag: tags
    menu:
      main:
        - name: Recherche
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

Params:
  editPost:
    URL: "https://gitlab.thalesdigital.io/tsn/innovation/projects/blog/-/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  DateFormat: "2 Jan 2006"