apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    cert-manager.io/cluster-issuer: acme-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64K
spec:
  ingressClassName : nginx
  rules:
    - host: blog.innovation.forthales.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-service
                port:
                  number: 80
  tls:
    - hosts:
        - blog.innovation.forthales.com
      secretName: blog-tls