apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS50aGFsZXNkaWdpdGFsLmlvL3Rzbi9pbm5vdmF0aW9uL3Byb2plY3RzL2Jsb2ciOnsidXNlcm5hbWUiOiJhcm5hdWQuYXltZXMiLCJwYXNzd29yZCI6IlltdGpTcHJEeW8zdXhKc1pEYkdmIiwiZW1haWwiOiJhcm5hdWQuYXltZXNAdGhhbGVzZ3JvdXAuY29tIiwiYXV0aCI6IllYSnVZWFZrTG1GNWJXVnpPbGx0ZEdwVGNISkVlVzh6ZFhoS2MxcEVZa2RtIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
